[Component] Update UIKit version of the Switch
adevinta/spark-ios pull request #210
Opened 2023-06-29 15:27 UTC by robergro

- Add optional init on Either
- Add String/AttributedString management
- Update SwitchImage to use Either
- Add Compression resistance priority
- Update demo

2023-07-03 07:51 UTC, LouisBorleeAdevinta requested changes

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Common/Enum/Either.swift
> +extension Either {
Doesn't make any sense, why? 🤔

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/SwitchTextContent.swift
> +protocol SwitchTextContentable{
missing space before {

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/SwitchTextContent.swift
> +protocol SwitchTextContentable{
naming should be `SwitchTextContent` like we did with tokens, when it's not an action, the name stays (like `any View` is not `any Viewable`)

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/SwitchTextContent.swift
> +struct SwitchTextContent: SwitchTextContentable {
and make it Default

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +protocol SwitchVariantable {
same thing as above regarding naming

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/TypeAlias/SwitchTypeAlias.swift
> +public typealias SwitchUIVariantImages = (on: UIImage, off: UIImage)
Should be a struct, tuples are bad

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/TypeAlias/SwitchTypeAlias.swift
> +public typealias SwitchVariantImages = (on: Image, off: Image)
Should be a struct, tuples are bad

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    init?(images: SwitchVariantImages?) {
shouldn'thave images as nillable in inits because it doesn't make any sense creating a SwitchVariant without it, it should be managed in dev like
```
guard let images = ... else { }
let switchVariant = init(images: images)
```

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    init?(images: SwitchUIVariantImages?) {
same

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    func toImages() -> SwitchVariantImages {
it isn't a conversion, getImages would be a bit clearer

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    func toUIImages() -> SwitchUIVariantImages {
same

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/UseCase/GetImage/SwitchGetImageUseCase.swift
> +                 variant: SwitchVariantable?) -> SwitchImage?
switch variant should never be nil and so neither should the returned value

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/UseCase/GetTextContent/SwitchGetTextContentUseCase.swift
> +struct SwitchGetTextContentUseCase: SwitchGetTextContentUseCaseable {
this usecase seems pointless 🤔

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/UseCase/GetToggleState/SwitchGetToggleStateUseCase.swift
> +    ) -> SwitchToggleStateable {
naming `SwitchToggleState + SwitchToggleStateDefault`

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/View/UIKit/SwitchUIView.swift
> +        label.setContentCompressionResistancePriority(.required,
I don't think we should make .horizontal required

2023-07-03 07:51 UTC, LouisBorleeAdevinta commented on spark/Demo/Classes/View/Components/Switch/SwitchTextContent.swift
> +    }
shouldShow....

show is more a wording for funcs

2023-07-03 09:59 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/SwitchTextContent.swift
> +protocol SwitchTextContentable{
DONE

2023-07-03 09:59 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/SwitchTextContent.swift
> +struct SwitchTextContent: SwitchTextContentable {
DONE

2023-07-03 10:00 UTC, robergro commented on core/Sources/Components/Switch/UseCase/GetToggleState/SwitchGetToggleStateUseCase.swift
> +    ) -> SwitchToggleStateable {
DONE

2023-07-03 10:00 UTC, robergro commented on core/Sources/Components/Switch/UseCase/GetTextContent/SwitchGetTextContentUseCase.swift
> +struct SwitchGetTextContentUseCase: SwitchGetTextContentUseCaseable {
DONE

2023-07-03 10:01 UTC, robergro commented on core/Sources/Common/Enum/Either.swift
> +extension Either {
Removed

2023-07-03 14:48 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +protocol SwitchVariantable {
Class is now removed

2023-07-03 14:48 UTC, robergro commented on core/Sources/Components/Switch/UseCase/GetImage/SwitchGetImageUseCase.swift
> +                 variant: SwitchVariantable?) -> SwitchImage?
DONE

2023-07-03 14:48 UTC, robergro commented on core/Sources/Components/Switch/TypeAlias/SwitchTypeAlias.swift
> +public typealias SwitchVariantImages = (on: Image, off: Image)
DONE

2023-07-03 14:49 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    init?(images: SwitchVariantImages?) {
Class is now removed

2023-07-03 14:49 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    func toImages() -> SwitchVariantImages {
Class is now removed

2023-07-03 14:49 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    func toUIImages() -> SwitchUIVariantImages {
Class is now removed

2023-07-03 14:49 UTC, robergro commented on core/Sources/Components/Switch/Model/Internal/Variant/SwitchVariant.swift
> +    init?(images: SwitchUIVariantImages?) {
Class is now removed

2023-07-03 15:34 UTC, LouisBorleeAdevinta requested changes

2023-07-03 15:34 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
> +        self.attributedText = nil
I don't think it should remove attributedText

2023-07-03 15:34 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
> +        self.text = nil
I don't think it should remove text

2023-07-03 15:34 UTC, LouisBorleeAdevinta commented on spark/Demo/Classes/View/Components/Switch/SwitchComponentItemsUIView.swift
> +        isImages: Bool,
hasImages

2023-07-04 07:14 UTC, robergro commented on core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
> +        self.attributedText = nil
I did the test and you're right, it's useless, I made the modification

2023-07-04 07:14 UTC, robergro commented on core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
> +        self.text = nil
I did the test and you're right, it's useless, I made the modification

2023-07-04 07:26 UTC, robergro commented on core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
> +        self.attributedText = nil
Ok, it's DONE. I removed all text and attributed text on ViewModel (and TextContent model) because it's just a get set on the view now

2023-07-04 07:26 UTC, robergro commented on core/Sources/Components/Switch/ViewModel/SwitchViewModel.swift
> +        self.text = nil
Same, DONE

2023-07-04 07:38 UTC, robergro commented on spark/Demo/Classes/View/Components/Switch/SwitchComponentItemsUIView.swift
> +        isImages: Bool,
DONE

2023-07-06 14:13 UTC, LouisBorleeAdevinta approved these changes

2023-07-07 06:46 UTC, merged