[Tab#234] The UI tab control comoponent
adevinta/spark-ios pull request #338
Opened 2023-08-22 09:52 UTC by michael-zimmermann

This is the UIKit implementation of the tab control.

This item was split into several smaller tasks, each of which had seperate PRs and were merged to this PR.
See:
- https://github.com/adevinta/spark-ios/pull/337
- https://github.com/adevinta/spark-ios/pull/332
- https://github.com/adevinta/spark-ios/pull/320
- https://github.com/adevinta/spark-ios/pull/310
- https://github.com/adevinta/spark-ios/pull/287
- https://github.com/adevinta/spark-ios/pull/274
- https://github.com/adevinta/spark-ios/pull/269
- https://github.com/adevinta/spark-ios/pull/258
- https://github.com/adevinta/spark-ios/pull/250
- https://github.com/adevinta/spark-ios/pull/248

### Pull requests template

This pull request has:
- [x] Code documentation on publics
- [x] Accessibility
	- [x] Dynamic sizes
	- [x] Identifiers
- [x] Tests
- [x] Demo update
- [ ] Wiki

2023-08-30 14:29 UTC, robergro submitted a review, later dismissed

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Common/UIKit/Extension/UIView/UIView-Attributes.swift
> +}
I don't feel it's really necessary

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCaseTests.swift
> +                       "Wrong vertical value")
Why did you change this? 
Horizontal is still `horizontalSpacing`, take one of the two :D

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCaseTests.swift
> +                       "Wrong vertical value")
same

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/UseCases/TabGetStateAttributesUseCase.swift
> +    static let xtraSmall: CGFloat = 34
extraSmall

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabUIView.swift
> +                content: [(UIImage?, String?)]
you could do name the variables like [(icon: UIImage?, title: String?)]
Usualy I avoid using tuples tho because it's not easy to init, you can't do a `.init(icon:, title:)` (I use structs instead)

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabUIView.swift
> +        self.invalidateIntrinsicContentSize()
Maybe not needed if `self.segments[safe: index]` returns nil

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabUIView.swift
> +        self.invalidateIntrinsicContentSize()
Maybe not needed if `self.segments[safe: index]` returns nil

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabUIView.swift
> +        self.invalidateIntrinsicContentSize()
Maybe not needed if `self.segments[safe: index]` returns nil

2023-09-07 07:57 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabUIView.swift
> +                                   icon: $0.icon) }
indentation is a bit weird here

2023-09-07 10:29 UTC, michael-zimmermann commented on core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCaseTests.swift
> +                       "Wrong vertical value")
To be honest, I don't know how the change got there. I imagine through a rebase.

2023-09-07 10:29 UTC, michael-zimmermann commented on core/Sources/Components/Button/UseCase/GetSpacings/ButtonGetSpacingsUseCaseTests.swift
> +                       "Wrong vertical value")
same as above

2023-09-07 10:30 UTC, michael-zimmermann commented on core/Sources/Common/UIKit/Extension/UIView/UIView-Attributes.swift
> +}
No, it is not necessary. But it makes filtering easier:
`self.stackView.arrangedSubviews.filter(\.isNotHidden)`
which I use in a few places.

2023-09-12 12:47 UTC, LouisBorleeAdevinta approved these changes

2023-09-13 09:51 UTC, LouisBorleeAdevinta requested changes

2023-09-13 09:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabItemUIView.swift
> +    ) {
Indentation issue

2023-09-13 09:51 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Tab/View/UIKit/TabItemUIView.swift
> +        apportionsSegmentWidthsByContent: Bool = false
not used?

2023-09-13 09:57 UTC, michael-zimmermann commented on core/Sources/Components/Tab/View/UIKit/TabItemUIView.swift
> +        apportionsSegmentWidthsByContent: Bool = false
Oh, yes. I'll correct it.

2023-09-13 11:53 UTC, LouisBorleeAdevinta approved these changes

2023-09-13 11:55 UTC, merged