[Component-376] Add ProgressBar for SwiftUI
adevinta/spark-ios pull request #552
Opened 2023-10-18 15:49 UTC by robergro

### Pull requests template

This pull request has:
- [ ] Code documentation on publics
- [ ] Accessibility
	- [ ] Dynamic sizes
	- [ ] Identifiers
- [ ] Tests
- [ ] Demo update
- [ ] Wiki

2023-10-19 14:06 UTC, michael-zimmermann reviewed
I'll finish looking at it later.

2023-10-19 14:06 UTC, michael-zimmermann commented on core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarDoubleView.swift
> +                    .width(
as mentioned above, I wouldn't make a very generic component dependent on a very specific view model.
Maybe the `if` part can be moved here and the `width` renamed to something more descriptive.

2023-10-19 14:26 UTC, michael-zimmermann requested changes
<img width="631" alt="Screenshot 2023-10-19 at 16 26 08" src="https://github.com/adevinta/spark-ios/assets/128726463/0b0c2260-99d1-4509-92b1-364cc77d9d11">
Please fix the compile errors, so I can test the component.

2023-10-20 15:11 UTC, michael-zimmermann reviewed
Just some comments and questions.
The demo looks good 🥇

2023-10-24 11:52 UTC, michael-zimmermann reviewed
just some small comments and questions

2023-10-27 15:26 UTC, robergro commented on core/Sources/Components/ProgressBar/View/SwiftUI/Internal/ProgressBarRectangle.swift
> +        viewModel: ProgressBarValueViewModel
Yes, you're absolutely right ! 
So:
- I move this code inside the common folder
- rename the function to proportionalWidth
- delete the viewModel parameter

And the if is now directly on the parent View

2023-10-27 15:39 UTC, robergro commented on core/Sources/Components/ProgressBar/View/SwiftUI/Public/ProgressBarIndeterminateView.swift
> +        .onReceive(self.viewModel.$animationStatus) { status in
I did that here because I prefer to have a timer inside a view and not the ViewModel (and also because the view model in our case is generic for SwiftUI and UIKit and we don't need to have a timer on UIKit).

2023-10-30 08:16 UTC, michael-zimmermann approved these changes

2023-10-30 15:34 UTC, michael-zimmermann approved these changes

2023-11-03 13:32 UTC, michael-zimmermann approved these changes

2023-11-03 14:05 UTC, merged