Checkbox bug 876
adevinta/spark-ios pull request #877
Opened 2024-04-05 06:49 UTC by aycil-alican

- I tried to fix all accessibility issue. 
- I removed indexes from checkbox identifier for items which are in checkbox group. I dont know If we change checkbox identifier in checkbox group as adding index.
-  I marked checkbox group as an list type. this mean; when client click space that isn't accessible part on checkbox group, First; Voice over will read checkbox group label or hint if they exist. I didn't specify from component side but consumer might set.
- I also didn't give trait to single checkbox item. Lots of app specify checkbox type  giving a value property.  ex: 
accessibilityValue = "Checkbox checked" or "Checkbox unchecked".

2024-04-05 09:04 UTC, LouisBorleeAdevinta requested changes

2024-04-05 09:04 UTC, LouisBorleeAdevinta commented on spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxGroupView.swift
> +//                .accessibilityLabel("I am checkbox group")
set accessibilityLabel from the title, if it doesn't have any do no set one

2024-04-05 09:04 UTC, LouisBorleeAdevinta commented on spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
> +//        self.updateCheckboxGroupAccessibility()
done in the component, remove

2024-04-05 09:04 UTC, LouisBorleeAdevinta commented on spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
> +    }
done in the component, remove

2024-04-05 11:04 UTC, aycil-alican commented on core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift
> +    public static let ticked = "1"
You are right I miss it I will add it

2024-04-05 11:13 UTC, aycil-alican commented on core/Sources/Components/Checkbox/Model/CheckboxGroupViewModel.swift
> -        self.accessibilityIdentifierPrefix = accessibilityIdentifierPrefix
I will add index at the end of identifier do we need to get prefix from consumer?

2024-04-05 11:19 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> +        .accessibilityRemoveTraits(.isButton)
If we keep buttun traits Voiceover will read it. ex: "Hello World" for label + "Checked" + "button" + "isSelected". When I checked other apps, they remove .button, and .selected states. They inform the user only value property. Ex;  "Hello World" for label + "Checkbox checked/unchecked" for value. That is why I removed button traits.

2024-04-05 11:19 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
> +        self.accessibilityContainerType = .semanticGroup
It might be I will change

2024-04-05 11:50 UTC, aycil-alican commented on spark/Demo/Classes/View/Components/Checkbox/SwiftUI/CheckboxGroupView.swift
> +//                .accessibilityLabel("I am checkbox group")
This was for you to show How consumer override the checkbox group with label or hints.  If you have already tested or not needed, I might remove it permanantly.

2024-04-05 11:51 UTC, aycil-alican commented on spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
> +//        self.updateCheckboxGroupAccessibility()
same it above, It was for the test

2024-04-05 11:55 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> -        }
If we keep buttun traits Voiceover will read it. ex: "Hello World" for label + "Checked" + "button" + "isSelected". When I checked other apps, they remove .button, and .selected states. They inform the user only value property. Ex; "Hello World" for label + "Checkbox checked/unchecked" for value. That is why I removed button traits.

2024-04-05 11:55 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> -        }
If we keep buttun traits Voiceover will read it. ex: "Hello World" for label + "Checked" + "button" + "isSelected". When I checked other apps, they remove .button, and .selected states. They inform the user only value property. Ex; "Hello World" for label + "Checkbox checked/unchecked" for value. That is why I removed button traits.

2024-04-05 18:27 UTC, aycil-alican commented on core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift
> +    public static let unticked = "0"
fixed

2024-04-05 18:28 UTC, aycil-alican commented on core/Sources/Components/Checkbox/AccessibilityIdentifier/CheckboxAccessibilityIdentifier.swift
> +    public static let ticked = "1"
fixed

2024-04-05 18:28 UTC, aycil-alican commented on core/Sources/Components/Checkbox/Model/CheckboxGroupViewModel.swift
> -        self.accessibilityIdentifierPrefix = accessibilityIdentifierPrefix
fixed

2024-04-05 18:28 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> +        .accessibilityValue(self.viewModel.selectionState == .selected ? CheckboxAccessibilityValue.ticked : CheckboxAccessibilityValue.unticked)
fixed

2024-04-05 18:28 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> +        .accessibilityRemoveTraits(.isButton)
fixed

2024-04-05 18:28 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> -        }
fixed

2024-04-05 18:29 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
> +        self.accessibilityContainerType = .semanticGroup
we decided to keep as it is

2024-04-05 18:30 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
> +        self.accessibilityTraits = self.isEnabled ? [.none] : [.notEnabled]
I had to manage enable case manually because after remove .selected trait from UIController, It cant specify .notEnabled case automatically

2024-04-05 18:33 UTC, aycil-alican commented on spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
> +//        self.updateCheckboxGroupAccessibility()
removed

2024-04-05 18:33 UTC, aycil-alican commented on spark/Demo/Classes/View/Components/Checkbox/UIKit/CheckboxGroup/CheckboxGroupComponentUIView.swift
> +    }
removed

2024-04-08 08:48 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
> +        }
at least I couldn't find how I should do that without .notEnabled trait

2024-04-08 08:53 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
>      }
As I said above After I removed .selected trait I couldn't manage .notEnabled automatically. That is why I added If you know the reason of this I might change.

2024-04-08 08:54 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> +            CheckboxAccessibilityValue.indeterminate
fixed

2024-04-08 08:54 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxView.swift
> +            CheckboxAccessibilityValue.checked
fixed

2024-04-08 08:54 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxUIView.swift
> +        self.setAccessibilityValue(selectionState: self.selectionState)
fixed

2024-04-12 11:45 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
> +    @available(*, deprecated, message: "Please use init without accessibilityIdentifierPrefix. It was gived as a static string.")
gived -> given

2024-04-12 11:45 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
> +    @available(*, deprecated, message: "Please use init without accessibilityIdentifierPrefix. It was gived as a static string.")
gived -> given

2024-04-12 11:45 UTC, LouisBorleeAdevinta commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
> +    ///   - accessibilityIdentifierPrefix: All checkbox-views are prefixed by this identifier followed by the `CheckboxGroupItemProtocol`-identifier.
remove 
```swift
- accessibilityIdentifierPrefix: All checkbox-views are prefixed by this identifier followed by the `CheckboxGroupItemProtocol`-identifier.
```

2024-04-12 12:15 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/SwiftUI/CheckboxGroupView.swift
> +    @available(*, deprecated, message: "Please use init without accessibilityIdentifierPrefix. It was gived as a static string.")
thanks :) I am still improving my english

2024-04-12 12:16 UTC, aycil-alican commented on core/Sources/Components/Checkbox/View/UIKit/CheckboxGroupUIView.swift
> +    @available(*, deprecated, message: "Please use init without accessibilityIdentifierPrefix. It was gived as a static string.")
fixed

2024-04-12 12:17 UTC, LouisBorleeAdevinta approved these changes

2024-04-16 16:29 UTC, merged